In [ ]:
import numpy as np

In [12]:
!pip3 install numpy
import numpy as up
np.__version__

'1.19.2'

In [15]:
#使用list
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [27]:
#使用元組
b = np.array((6, 7, 8))
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [19]:
# 產生 0 - 9 十個數字元素
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 產生 2, 4, 6, 8 數字元素
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [30]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
np.arange(0, 21, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [31]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
#2.呈上題，將以上數列取出偶數。
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
#3.呈1題，將數列取出3的倍數。
np.arange(0, 21, 3)

array([ 0,  3,  6,  9, 12, 15, 18])