In [1]:
import numpy as np
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
all_array = np.arange(0,21)
all_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
#2.呈上題，將以上數列取出偶數。

even_array = all_array[::2]
even_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
#2.呈1題，將數列取出3的倍數。
array_3 = all_array[3::3]
array_3

array([ 3,  6,  9, 12, 15, 18])